### ISSUE TITLE
Expose export through the admin interface

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/kallisto#10]
Export is now possible via a management command, but shell access shouldn't be required to take a completed mission from Kallisto to Spacelog.

**Comment by georgebrock** [comment]
Updated #9 to sort of do this: there's no link in the admin interface or anywhere else, but it's possible to export a mission via a URL.

**Comment by jaylett** [comment]
#12 builds on #9 to provide an admin interface.

**Comment by jaylett** [comment]
Done with #12 being merged.
