### ISSUE TITLE
Management command for exporting to Spacelog

### ISSUE THREAD

**Issue by georgebrock** [Spacelog/kallisto#8]
It would be great if we could easily export:

* The cleaned transcript, as a single file.
* A basic metadata file, since Kallisto knows things like who did the cleaning.

**Comment by georgebrock** [comment]
I've started working on this, so we can get MA8 into Spacelog.

**Comment by georgebrock** [comment]
WIP here: https://github.com/Spacelog/kallisto/compare/master...georgebrock:export-command

**Comment by jaylett** [comment]
Thorge :+1:

**Comment by georgebrock** [comment]
Closing in favour of #9.
